### ISSUE TITLE
Draguino shield + Mega not compatible with Temboo

### ISSUE THREAD

**Issue by luzine** [dragino/modules#2]
A Arduino Mega with a Draguino Yun shield does not allow to compile sketch using Temboo choreo class. Anyone got it to work?

**Comment by dragino** [comment]
Same isse happen while use MEGA2560, this is the compaible issue on Temboo. please post the issue on Temboo support . Thank You.

**Comment by MisterCyp** [comment]
Replace in Temboo.h and Temboo.cpp the line :
    #if defined (ARDUINO_AVR_YUN) || defined (ARDUINO_AVR_TRE) 
by:
    #if defined (ARDUINO_AVR_YUN) || defined (ARDUINO_AVR_TRE) || defined (ARDUINO_AVR_MEGA2560)

It works !!
