### ISSUE TITLE
I updated firmware to 2.0.5 - now ide cant detect yun shield over wifi

### ISSUE THREAD

**Issue by Bulmer** [dragino/modules#4]
I have updated my Yun Shields firmware to common-2.0.5 but my Arduino IDE now fails to detect the Yun Shields ip address. I have everything else working perfectly (web gui admin, ssh access). What settings should I look at to ensure its detected ? I don't really want to go back to the 1.3.4 firmware.

**Comment by dragino** [comment]
this issue some sometimes happen in 1.3.4 as well. try /etc/init.d/avahi-daemon restart. more info about this issue is here: http://wiki.dragino.com/index.php?title=Yun_Shield#Arduino_IDE_doesn.E2.80.99t_detect_Yun_Shield

**Comment by Bulmer** [comment]
I tried all those suggestions and its still not being recognised. If I post my uci config here would you be able to look for any obvious problem?

**Comment by dragino** [comment]
the UCI config doesn't help on this. do you use wifi or cable? try several times of this:  /etc/init.d/avahi-daemon restart

**Comment by dragino** [comment]
which Arduino IDE version do you use?

**Comment by Bulmer** [comment]
I use Arduino 2:1.0.5+dfsg2-4 on Debian 8. Strangely I just tried an ide on Windows 7 and have managed to have it recognised and uploaded a sketch. Maybe its a problem with the Debian Arduino IDE?

**Comment by dragino** [comment]
When we use wireshark to capture the packets,  We see some times the Arduino IDE (in Windows) doesn't detect the device even the device send the discover message to the IDE. i think this is a bug in the IDE.

**Comment by zeeHacker** [comment]
I have the same issue here, I recently upgraded to FXS firmware now my IDE doesn't detect network port n I also lost the memory I had expanded... I had used the wget method from this [http://forum.arduino.cc/index.php?topic=321502.msg2227962#msg2227962](url) forum now I cant use wget, not recognised I guess... help please

**Comment by zeeHacker** [comment]
One issue down... found out that I needed to 'opkg install wget' and then I went back to that forum and followed the steps provided so my memory is expanded...but IDE still cant detect network port.

**Comment by dragino** [comment]
Hi, Zee,

 

The FXS firmware doesn’t have Avahi-daemon running so Arduino IDE can’t see it.  this feature only available on the IoT and Yun firmware. 

 

Best Regards,

Edwin 

 

 

 

发件人: zeeHacker [mailto:notifications@github.com] 
发送时间: 2016年4月14日 13:10
收件人: dragino/modules
抄送: edwin
主题: Re: [dragino/modules] I updated firmware to 2.0.5 - now ide cant detect yun shield over wifi (#4)

 

I have the same issue here, I recently upgraded to FXS firmware now my IDE doesn't detect network port n I also lost the memory I had expanded... I had used the wget method from this http://forum.arduino.cc/index.php?topic=321502.msg2227962#msg2227962 forum now I cant use wget, not recognised I guess... help please

**Comment by zeeHacker** [comment]
Thank you dragino for the response, had been looking all over for this. 
But is there another way of installing the avahi-daemon or at least another alternative for uploading sketches to the yun. I have fxs-3.1.0, please help I'm new to this.

**Comment by dragino** [comment]
Why do you want to stick on the fxs firmware? The gpios in this firmware is used for FXS VOIP module. you can’t use it to upload firmware to the Atmel MCU. 

 

发件人: zeeHacker [mailto:notifications@github.com] 
发送时间: 2016年4月14日 15:47
收件人: dragino/modules
抄送: edwin
主题: Re: [dragino/modules] I updated firmware to 2.0.5 - now ide cant detect yun shield over wifi (#4)

 

Thank you dragino for the response, had been looking all over for this. 
But is there another way of installing the avahi-daemon or at least another alternative for uploading sketches to the yun. I have fxs-3.1.0, please help I'm new to this.

**Comment by zeeHacker** [comment]
It is for my final year project, I'm developing a VoIP based Virtual UHF Radio...have never tried uploading .hex compiled sketches but I think I came across somewhere where mention was made of that, does that work?

**Comment by dragino** [comment]
If you want to upgrade the .hex to AVR, you can install avr-dude package and properly configure the GPIOs pin map. (need to rmmod the fxs kernel module first. ) : reference link: https://github.com/dragino/openwrt-bb-1407/tree/master/replacement-pkgs/avrdude 

If you want to see the device in Arduino IDE, you need to install avahi-daemon, and configure to broadcast the related info.  Additional files you need: https://github.com/dragino/openwrt-bb-1407/tree/master/files-yun/etc/avahi 

 

发件人: zeeHacker [mailto:notifications@github.com] 
发送时间: 2016年4月14日 17:44
收件人: dragino/modules
抄送: edwin
主题: Re: [dragino/modules] I updated firmware to 2.0.5 - now ide cant detect yun shield over wifi (#4)

 

It is for my final year project, I'm developing a VoIP based Virtual UHF Radio...have never tried uploading .hex compiled sketches but I think I came across somewhere where mention was made of that, does that work?

**Comment by zeeHacker** [comment]
Thank you, but how exactly do install and configure the avahi-daemon. The instructions in the README.md ( [https://github.com/dragino/openwrt-bb-1407/blob/master/README.md](url) ) are not quiet specific. As I said before I'm still quite new to Linux and Yun technology altogether... do I start by git clone? And were to from there? Thanks again for your support!
